trigger:
  branches:
    include:
    - main
    - feature/*
    - bugfix/*
  paths:
    include:
    - src
    - pom.xml
    - azure-pipelines.yml
    exclude:
    - README.md

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
  Agent.Source.Git.ShallowFetchDepth: 1

steps:
- task: MavenAuthenticate@0
  displayName: 'Maven Authenticate'
  inputs:
    artifactsFeeds: plsqlcop

- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'
    restoreKeys: |
      maven | "$(Agent.OS)"
      maven
    path: $(MAVEN_CACHE_FOLDER)
  displayName: Cache Maven local repo

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: for f in $(Pipeline.Workspace)/tvdcc-4.4.0*.jar; do echo $f; mv $f $(Pipeline.Workspace)/tvdcc.jar; done

- task: Maven@3
  displayName: 'Maven com.trivadis.tvdcc'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '$(MAVEN_OPTS)'
    goals: '-Dtvdcc.basedir=$(Pipeline.Workspace) -DaltDeploymentRepository=plsqlcop::default::https://pkgs.dev.azure.com/tvdvsts/2001.5038513/_packaging/plsqlcop/maven/v1 clean deploy -U'
    publishJUnitResults: true
    jdkVersion: 17
